apiVersion: v2
name: prometheus
appVersion: v2.46.0
version: 24.1.0
kubeVersion: ">=1.19.0-0"
type: application
dependencies:
  - name: alertmanager
    version: "1.6.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: alertmanager.enabled
  - name: kube-state-metrics
    version: "5.11.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-state-metrics.enabled
  - name: prometheus-node-exporter
    version: "4.22.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-node-exporter.enabled
  - name: prometheus-pushgateway
    version: "2.4.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-pushgateway.enabled
keywords:
  - monitoring
  - prometheus